server:
  port: 8812
#db1库
spring.datasource.db1:
  url: jdbc:mysql://localhost:3306/haoak?characterEncoding=UTF-8
  username: root
  password: 123456
  driver-class-name: com.mysql.jdbc.Driver
#db2库
spring.datasource.db2:
  url: jdbc:mysql://localhost:3308/haoak?characterEncoding=UTF-8
  username: root
  password: 123456
  driver-class-name: com.mysql.jdbc.Driver