server:
  port: 8812
#db1库
spring.datasource.db1:
  jdbc-url: jdbc:mysql://localhost:3306/haoak?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
  username: root
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver
#db2库
spring.datasource.db2:
  jdbc-url: jdbc:mysql://localhost:3308/ankhao?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
  username: root
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver

management.endpoint.shutdown.enabled: true
management.endpoints.web.exposure.include: "*"