server:
  address: localhost
  port: 8845
  servlet:
    context-path: /bs/job
spring:
  application:
    name: scheduler
#  datasource:
#    url: jdbc:oracle:thin:@10.100.1.23:1521:acgist
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    username: test
#    password: test
#  datasource:
#    url: jdbc:mysql://10.100.1.115:3306/bg_schedule?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&amp
#    username: root
#    password: bangsun
#    driver-class-name: com.mysql.cj.jdbc.Driver

    #Oracle
#    platform: oracle
#    url: jdbc:oracle:thin:@10.100.1.210:2521:xe
#    username: smartlearning_pretest
#    password: 123456
#    driver-class-name: oracle.jdbc.driver.OracleDriver
portal.jdbc:
  type: mysql
  maximumPoolSize: 10
  jdbcUrl: jdbc:mysql://10.100.1.115:3306/bg_schedule?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: bangsun

#  quartz:
#    properties:
#      org:
#        quartz:
#          job-store-type: jdbc
#          jdbc:
#            initialize-schema: never
#          scheduler:
#            instanceName: smQuartzScheduler
#            instanceId: AUTO
#            skipUpdateCheck: true
#          threadPool:
#            class: org.quartz.simpl.SimpleThreadPool
#            threadCount: 5
#            threadPriority: 5
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            useProperties: false
#            tablePrefix: ML_QRTZ_
#            isClustered: true
#            clusterCheckinInterval: 20000
#            dataSource: sm
#          dataSource:
#            sm:
#              driver: ${spring.datasource.driver-class-name}
#              URL: ${spring.datasource.url}
#              user: ${spring.datasource.username}
#              password: ${spring.datasource.password}
#              maxConnections: 5
#              validationQuery: select 1 from dual
#              connectionProvider.class: cn.com.bsfit.scheduler.core.config.AnkConnectionProvider


#eureka:
#  instance:
#    prefer-ip-address: false
#    instance-id: ${server.address}:${spring.application.name}:${server.port}
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://eureka-0.eureka:8761/eureka/,http://eureka-1.eureka:8761/eureka/
##心跳间隔，单位秒
ank.scheduler:
  heartbeat-interval: 30
##日志
logstash:
  ip: ml.kibana
  port: 9250
##jdbc监控
opentracing.spring.cloud.jdbc.enabled: false

portal:
  security:
    actuator:
      username: actuator
      sha256password: 114a862e248fe7387337b293878c80833fcf6d6072896af26cb8c14ac0d19728